name: Package Application for Windows with Pyinstaller

on:
  push:
    branches: [ main, dev ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Package Application
      uses: ./action_windows_pkg
      with:
        path: ./

    - uses: actions/upload-artifact@v2
      with:
        name: a_table
        path: ./dist/windows
